version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: green-mongodb
    networks:
      - my-network
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo_data:/data/db

  express-app:
    image: express-app:${COMMIT_ID}
    container_name: green-express-app
    networks:
      - my-network
    environment:
      MONGO_URI: "mongodb://admin:password@green-mongodb:27017/mydatabase?authSource=admin"
    ports:
      - "5011:5011"

  react-app:
    image: react-app:${COMMIT_ID}
    container_name: green-react-app
    networks:
      - my-network
    environment:
      VITE_DEV_API_URL: "http://localhost:5011/api/auth"
    ports:
      - "5173:5173"

networks:
  my-network:
    driver: bridge

volumes:
  mongo_data:
