pipeline {
    agent any

    environment {
        AWS_REGION = 'us-east-1'
        ECR_REPO = '148761653007.dkr.ecr.us-east-1.amazonaws.com/final-project/express-app'
        AWS_ACCOUNT_ID = '148761653007'
        IMAGE_NAME = 'express-app'
        GOOGLE_CHAT_WEBHOOK_URL = 'https://chat.googleapis.com/v1/spaces/AAAAp5VSxZk/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=3ZhaGsdiFysc2U8mS_31mNQGlvFh2mm1zMVSHJj0bh0'
    }

    stages {
        stage('Checkout Code') {
            steps {
                checkout scm
            }
        }

        stage('Get Short Commit ID') {
            steps {
                script {
                    def commitID = sh(script: "git rev-parse HEAD", returnStdout: true).trim()
                    env.SHORT_COMMIT_ID = commitID[0..6]
                    echo "Using commit ID: ${env.SHORT_COMMIT_ID}"
                }
            }
        }

        stage('Login to AWS ECR') {
            steps {
                script {
                    sh """
                    aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com
                    """
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    sh """
                    docker build -t ${IMAGE_NAME}:${env.SHORT_COMMIT_ID} .
                    docker tag ${IMAGE_NAME}:${env.SHORT_COMMIT_ID} ${ECR_REPO}:${env.SHORT_COMMIT_ID}
                    """
                }
            }
        }

        stage('Push Image to ECR') {
            steps {
                script {
                    sh """
                    docker push ${ECR_REPO}:${env.SHORT_COMMIT_ID}
                    """
                }
            }
        }

        stage('Cleanup Docker Images') {
            steps {
                script {
                    sh """
                    docker rmi -f \$(docker images -q) || true
                    docker system prune -a -f || true
                    """
                }
            }
        }
    }

    post {
        success {
            script {
                def message = """
                {
                    "text": "✅ Jenkins Pipeline Success! Deployed ${IMAGE_NAME}:${env.SHORT_COMMIT_ID} to ${params.NAMESPACE}."
                }
                """
                sh """
                curl -X POST -H 'Content-Type: application/json' --data '${message}' '${env.GOOGLE_CHAT_WEBHOOK_URL}'
                """
            }
        }
        failure {
            script {
                def message = """
                {
                    "text": "❌ Jenkins Pipeline Failed! Check logs."
                }
                """
                sh """
                curl -X POST -H 'Content-Type: application/json' --data '${message}' '${env.GOOGLE_CHAT_WEBHOOK_URL}'
                """
            }
        }
    }
}